# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GoChat' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'Firebase/Core'
    pod 'Firebase/Auth'
    pod 'GoogleSignIn'
    pod 'JSQMessagesViewController'
    pod 'Firebase/Database'
    pod 'Firebase/Storage'
    pod 'SDWebImage'
    pod 'Firebase/RemoteConfig'
    pod 'Fabric', '~> 1.9.0'
    pod 'Crashlytics', '~> 3.12.0'

  # Pods for GoChat

end
